openSUSE/mksusecd

- mksusecd
These are the modules necessary to mount a squashfs image.
> adjust list of specially handled initrd modules

- mksusecd
And generally add support for Tumbleweed images.
TW uses images to deploy the system; these files were not yet taken into account by mksusecd.
> - sanitize function that removes files from iso

- mksusecd
modules.builtin can just be copied; in modules.order the paths must be
adjusted, as all our modules reside in the 'initrd' subdirectory.
> handle modules.order and modules.builtin when updating a kernel

- mksusecd
As a result of bsc#991935 automatically adding add-ons via
add_on_products.xml during installation works again. This patch adds support
for this feature to mksusecd.
> support creating add-ons on the target iso (bsc #991935)

- mksusecd
modutils used to put the modules with full path into modules.dep
('/lib/modules/&lt;VERSION>/kernel/fs/xfs/xfs.ko').
Newer versions have just the relative path ('kernel/fs/xfs/xfs.ko').
The patch changes the entries from the old to the new format.
> fix to work with older modules.dep format (bsc #1027636)

- mksusecd
Normally, changes are just appended to the initrd. This avoids needing root
permissions to run mksusecd. (The problem is that device nodes can't be re-packed
without root permissions.)
With this option we re-pack the entire initrd.
(Needed for bsc#1027636.)
> add --rebuild-initrd option for smaller initrds

- mksusecd
There are some Lenovo Thinkpad notebooks that don't like to see an iso9660
file system when booting via UEFI from usb disk.
So, the '--fat' option allows you to create images for disks but they are no
longer usable to burn dvds.
> remove iso9660 header when creating image for usb media (bsc #939456)

- mksusecd
See 'mksusecd --help' for usage and
https://lizards.opensuse.org/2017/11/17/encrypted-installation-media for an example.
Hackweek project page: https://hackweek.suse.com/16/projects/encrypted-installation-media
> allow building of encrypted installation media

- mksusecd
Sub-functions read_write() and write_pad_and_close() were not correctly
constructed.
In the old code subsequent calls to unpack_cpiox() had read_write() and
write_pad_and_close() still reference the old set of local variables from
the first unpack_cpiox() call.
> fix cpio archive parser (bsc #1092147)

- mksusecd
isoinfo adds an additional first column in some cases.
syslinux meanwhile needs root privileges.
> adjust to isoinfo and syslinux changes (bsc #1097814)

- mksusecd
Else we might not be able to mount squashfs images.
> don't miss zstd compression module

- mksusecd
In the beginning the intention was that the new repo-md repositories would
not include the installer itself. But that idea has been dropped, so we
should no longer assume the instsys will not be there.
Instead the new option --[no-]instsys-in-repo is used to explicitly control this.
> no longer assume repo-md repositories don't include the installer (bsc #1093145

- mksusecd
Latest checkmedia supports verification of images via an embedded  signature over checksum metadata. Also, latest SUSE build tools do it.
mksusecd can do it.
https://github.com/openSUSE/checkmedia/pull/10
> embed gpg signature of checksum metadata into image (bsc#1139561)

- mksusecd
While working on https://bugzilla.suse.com/show_bug.cgi?id=1141223 some outstanding issues on s390 media were identified and fixed.
Note that these issues seem (so far) not related to the problem described in the bug report.
`mksusecd` does not update all files consistently on s390 media.
1. write new initrd size into `boot/s390x/initrd.siz`
2. recreate `boot/s390x/cd.ikr` (kernel + initrd + kernel options, combined into a single image)
3. `--boot` has now an effect on s390 (updates `boot/s390x/parmfile` and `isozipl` uses it)
> adjust boot files for s390x (bsc#1141223)

- mksusecd
https://bugzilla.suse.com/show_bug.cgi?id=1158131
mksusecd does not pick the correct kernel image on aarch64.
It's `Image-*`. And add a comment showing the names in our kernel packages.
> choose correct kernel image name for aarch64 (bsc #1158131)

- mksusecd
- https://bugzilla.suse.com/show_bug.cgi?id=1173263
`mksusecd` includes all products from the full iso even if `--include-repos` specifies only a subset.
1. The existing code assumed that the full iso was a separate image. So it included everything from the first image, not matter what. That's no longer true with the full sp2 iso.
1. The second issue is that the new full iso uses subdirectories with names different from the repo name. So the code had to be adjusted for that as well. Otherwise the generated iso would have put the products into differently named subdirectories, which might be confusing to users.
1. `media.1/products` didn't get its checksum entry updated, fixed this as well.
> do not include excluded products (bsc#1173263)

- mksusecd
So far, mksusecd allowed only to use a secret key file to specify the signing key.
It is more useful to specify the key id that gpg should use.
Add new `--sign-key-id` option that accepts a gpg key id.
**Note:** This implies that there might be an interactive password prompt to unlock the key.
> add --sign-key-id option to allow specifying a gpg signing key by id

- mksusecd
- https://bugzilla.suse.com/show_bug.cgi?id=1176176
- https://trello.com/c/HoAiJKC4
With the new full media layout, `--include-repos` did not limit the included product and module parts under certain circumstances (i.e. working on an unpacked ISO).
There are several parts:
1. look only at the toplevel products file `media.1/products`, not at their conterparts in the product or module subdirectories
1. the newly created products file did not end up on the generated media due to a bug when merging directories
1. products may be on a single medium (as in sle15-sp2) or distributed on several media (as in sle15-sp1)
The created media are (AFAICS) correct. But (sle15-sp2 only):
yast may run into an internall error at startup: `undefined method `license_confirmation_required?'`.
This seems to be …
> fix product handling with new SLE full media layout

- mksusecd
- https://bugzilla.suse.com/show_bug.cgi?id=1176379#c15
`add_on_products.xml` is used for adding add-ons and for auto-enabling product repositories. Ensure both functions work together.
Otherwise using both `--addon` and `--enable-repos` option at the same time might end up creating a wrong `add_on_products.xml` or make `mksiosfs` fail.
`new_file()` does the same as the code it replaces (create the file in a temporary directory) but it also updates the internal database tracking files for the later `mkisofs` call to ensure the correct version of the file is added to the final image.
> fix add_on_products.xml handling (bsc#1176379)

- mksusecd
- https://bugzilla.suse.com/show_bug.cgi?id=1182573
With SLE15-SP3 and current Tumbleweed kernel modules are compressed and have a `.ko.xz` extension. Adjust mksusecd to handle these.
> handle .ko.xz modules (bsc#1182573)

- mksusecd
- obs/mksusecd.spec
- support RH media https://jira.suse.com/browse/SCL-6
- support `skelcd-installation-xxx` packages as input source
- add new `--instsys` option to easily change/extend the installation system
This requires the latest [checkmedia >= v6.0](https://github.com/openSUSE/checkmedia) to work (to embed RH style checksums).
To update a SLES medium with the latest installer build, you can now do:
```
```
To insert a new anaconda config living in `/tmp/foo`, for example:
```
/tmp/foo
/tmp/foo/etc
/tmp/foo/etc/anaconda
/tmp/foo/etc/anaconda/conf.d
/tmp/foo/etc/anaconda/conf.d/20-my-config.conf
```
you can do:
```
```
> add support for rh media (jsc#SCL-6)

- mksusecd
The recently added zstd compression code contained a typo breaking proper compression type detection.
> fix zstd compression handling

- mksusecd
Some modules have to be treated specially at system startup. These are modules needed to access the compressed initrd parts.
In recent systems, a file `.base_modules` exists in the initrd containing a list of these modules. Older systems relied on a hard coded list.
> read list of special initrd modules from .base_modules if it exists

- mksusecd
- mksusecd_man.adoc
- https://jira.suse.com/browse/SLE-22669
mksusecd can already use `skelcd-installer-<PRODUCT>` as input source. Handle `tftpboot-installation-<PRODUCT>` in the same way (it contains the same data but in a different location).
The benefit is that  `tftpboot-installation-<PRODUCT>` are available as part of our usual openSUSE/SLE products and are updated regularly. This way you can easily rebuild the openSUSE/SLE installation media with the latest installer updates.
```
mksusecd --create new.iso openSUSE-Tumbleweed.iso tftpboot-installation-openSUSE-Tumbleweed-x86_64-17.28-1.1.noarch.rpm
```
> support tftpboot-installation-<PRODUCT> RPMs as source (jsc#SLE-22669)

- mksusecd
mksusecd failed to handle current Tumbleweed kernels.
After usrmerge the kernel package layout changed a bit; in particular:
- `/usr/lib` instead of `/lib`
- files moved from `/boot` to `/usr/lib/KERNEL_VERSION`
- no version suffix in these files anymore
**Bonus**
- warn if module tools are too old to handle kernel module format
> fix handling of usrmerge kernels

- mksusecd
- mksusecd_man.adoc
- https://bugzilla.suse.com/show_bug.cgi?id=1206181
Implement a better handling of usrmerge kernels.
This is a follow-up of https://github.com/openSUSE/mksusecd/pull/63.
The original approach causes problems on architectures that have their shared library linker in `/lib` (and not in `/lib64`) - like aarch64.
This new patch fixes these inconsistencies and as a bonus allows to use usrmerge kernels on non-usrmerge media and vice versa (for example, a Tumbleweed kernel on SLE15).
> much improved usrmerge kernel support (bsc#1206181)

- mksusecd
- mksusecd_man.adoc
- https://bugzilla.suse.com/show_bug.cgi?id=1213185
Add option to allow having different ISO fs labels for the main file system and the ISO file system in the partition of a hybrid ISO.
> add --volume1 option to allow setting separate labels for both ISO file systems (bsc#1213185)

- isohybrid.c
- mksusecd
- mksusecd_man.adoc
- fix --instsys option handling (existing files were not replaced)
- fix --instsys option to take care of xattrs (selinux atributes)
- allow --instsys option for Live media
- calculate EFI boot image size correctly
- if initrd/kernel are in two different location on the medium, update in both locations
- add --rescue option to modify rescue system
- change signature block handling and make it visible as .signature per default
> - allow --instsys option for Live media

- mksusecd
- https://bugzilla.suse.com/show_bug.cgi?id=1218706
Recently, Tumbleweed started using zstd in its repo metadata.
For example, `/repodata/<SHA256>-primary.xml.zst`.
Asjust mksusecd to support zstd (and xz, just in case).
> allow also xz and zstd compression in repodata (bsc#1218706)

- README.md
- mksusecd
- mksusecd_man.adoc
- https://bugzilla.suse.com/show_bug.cgi?id=1214789
Tumbleweed and SLE15-SP6 switched to using compressed kernel firmware files in the installation system.
> handle compressed firmware files (bsc#1214789)

- mksusecd
- https://bugzilla.suse.com/show_bug.cgi?id=1221603
If `/tmp` is a symlink, mksusecd won't find temporarily mounted file systems when trying to unmount during cleanup.
> deal with systems where /tmp is a symlink (bsc#1221603)

- mksusecd
- https://bugzilla.suse.com/show_bug.cgi?id=1226047
Software modules (repos) containing debuginfo or source packages were not handled correctly. The newly generated product info was incorrect.
> fix integrating software modules containing debuginfo packages (bsc#1226047)

- mksusecd
- mksusecd_man.adoc
The Joliet ISO-9660 extension allows only for file names of up to 103 Unicode chars. Add useful warning if that limit is exceeded. Also, fix `--no-joliet` implementation.
> fix --no-joliet option and add warning about too long Joliet file names

- mksusecd
- https://bugzilla.suse.com/show_bug.cgi?id=1227668
If the `EFI` directory content is updated, rebuild `boot/ARCH/efi` to match.
The UEFI firmware might use either of these in the boot process.
> update El-Torito UEFI image to match 'EFI' directory (bsc#1227668)

- mksusecd
- https://bugzilla.suse.com/show_bug.cgi?id=1236828
Some KIWI generated ISO media don't have the UEFI boot image visible in the file system.
Enhance code to detect the UEFI boot config properly also in these cases and ensure a suitable UEFI boot image will be created.
> make a more determined attempt to create the UEFI boot image if it is missing (bsc#1236828)

- mksusecd
- mksusecd_man.adoc
- https://bugzilla.suse.com/show_bug.cgi?id=1236828
mksusecd used to require root to unpack ISO images (to mount them).
With this change this is no longer necessary - at the expense of consuming more temporary space in `/tmp`.
This allows ISO modifications to be done in the build system as normal user.
> do not require root permissions to unpack ISO images (bsc#1236828)

- obs/mksusecd.spec
- verifymedia
- verifymedia_man.adoc
- verifymedia depends on perl-JSON
- rework signature test wording to be more clear
- `--ignore` takes` only single argument
```
Verifying: SLE-15-SP5-Online-x86_64-QU1-Media1.iso
Check results: [✔] = ok, [✘] = bad, [!] = not ideal
[✔] image has ISO-9660 file system
[✔] image uses Rock Ridge extension
[✔] image uses Joliet extension
[✔] image has volume id
[✔] all files are world-readable
[✔] all files are owned by root
[✔] media style: suse
[✔] media variant: install
[✔] media architecture: x86_64
[✔] media layout supported
[✔] .treeinfo architecture matches
[✔] kernel and initrd referenced in .treeinfo exist
[✔] kernel exists
[✔] initrd exists
[✔] isolinux config exists
[✔] UEFI grub config exists
[✔] UEFI grub config references correct root file system
[✔] UEFI boot loader exists
[✔] …
```
> add missing perl-JSON dependency

- mksusecd
- https://bugzilla.suse.com/show_bug.cgi?id=1239528
So far only either entirely uncompressed or compressed multi-part initrds were supported.
> support dracut-style initrd (uncompressed cpio archive followed by compressed cpio archive) (bsc#1239528)

- mksusecd
- mksusecd_man.adoc
- verifymedia
- https://bugzilla.suse.com/show_bug.cgi?id=1241374
Enhance `verifymedia` to check red hat/fedora style media. This is useful for our multi linux (liberty) media.
> add red hat/fedora media support to verifymedia (bsc#1241374)
